#include <iostream>
using namespace std;
/*
1)They are directly usable in the same program and are used for declaring unique identifiers.
2)name of namespace is not mentioned in namespace in unnamed namespace
3)name of namespace is uniquely generated by compiler
4)The unnamed namespaces you have created will only be accessible within the file you created it in
5)unnamed namespace occupy global scope
*/

namespace
{
    int a=9;
    int b=90;
    void show()
    {
        cout<<"HI"<<endl;
    }
}

int main()
{
    int a=12;
    cout<<a<<"\nas unnamed namespace occupy global scope: "<<::a<<"\n"<<b<<endl;
    show();

}
